import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {

  const questionId = "1"

  return (

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Move below to own component? */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Suprising Scales
        </h1>

        <ul className={styles.fillblocks}>
          <li style={{ width: '10%' }} className={styles.fillblock}></li>
          <li style={{ width: '20%' }} className={styles.fillblock}></li>
          <li style={{ width: '60%' }} className={styles.fillblock}></li>
        </ul>

        <p className={styles.subtitle}>
          Do you know your scales from your fails?
        </p>

        <p className={styles.description}>
          Play through these 10 questions and match up the options to the size of the bar. The answers might suprise you!
        </p>

        <Link href={`/question/${questionId}`} passHref>
          <button className={styles.button}> Start </button>
        </Link>


      </main>

      <footer className={styles.footer}>
        Powered by Robo
      </footer>
    </div >
  )
}
